name: "Install dependencies"

description: "Cache node_modules and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      uses: actions/cache@v3
      id: yarn-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile